# Generated by Django 2.2.7 on 2021-05-07 18:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eMarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=False, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
