# Generated by Django 2.2.7 on 2021-05-09 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMarket', '0002_auto_20210507_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='favourite',
            field=models.ManyToManyField(blank=True, default=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
