# Generated by Django 4.1.6 on 2023-02-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMarket', '0007_auto_20210519_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, default=False, upload_to='media/'),
        ),
    ]
