# Generated by Django 4.1.6 on 2023-02-15 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eMarket', '0008_alter_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='favourite',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'SMALL'), ('M', 'MEDIUM'), ('L', 'LARGE'), ('E', 'EXTRALARGE')], max_length=20, null=True),
        ),
    ]
