# Generated by Django 4.1.6 on 2023-02-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMarket', '0009_alter_products_favourite_alter_products_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount_price',
            field=models.FloatField(default=0),
        ),
    ]
