# Generated by Django 4.1.6 on 2023-02-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMarket', '0012_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
