# Generated by Django 4.1.6 on 2023-02-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eMarket', '0013_alter_order_ref_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='export_reciept',
            field=models.BooleanField(default=False),
        ),
    ]
